name: Build and Push

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      context:
        required: false
        type: string
        default: .
    secrets:
      docker_hub_username:
        required: true
      docker_hub_password:
        required: true
      jwt_private_key:
        required: true
      jwt_public_key:
        required: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Create key directory
        run: mkdir -p ${{ inputs.backend-path }}/src/main/resources/keys

      - name: Inject JWT Keys
        run: |
          echo "${{ secrets.jwt_private_key }}" > ${{ inputs.backend-path }}/src/main/resources/keys/private_key.pem
          echo "${{ secrets.jwt_public_key }}"  > ${{ inputs.backend-path }}/src/main/resources/keys/public_key.pem
          shell: bash

      - name: Secure permissions for key files
        run: chmod 600 ${{ inputs.backend-path }}/src/main/resources/keys/*.pem

      - name: Build and Package
        run: ./mvnw clean package -B -DskipTests

      - name: Dockerhub Login
        if: contains(fromJSON('["refs/heads/main", "refs/heads/develop"]'), github.ref) || startsWith(github.ref, 'refs/heads/hotfix/')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_hub_username }}
          password: ${{ secrets.docker_hub_password }}

      - name: Extract metadata (tags, labels) for Docker
        if: contains(fromJSON('["refs/heads/main", "refs/heads/develop"]'), github.ref) || startsWith(github.ref, 'refs/heads/hotfix/')
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.REGISTRY }}/${{ inputs.image_name }}

      - name: Build and Push Docker Image
        if: contains(fromJSON('["refs/heads/main", "refs/heads/develop"]'), github.ref) || startsWith(github.ref, 'refs/heads/hotfix/')
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}