name: Frontend CI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Build environment"
        required: true
        default: "integration"
        type: choice
        options:
          - integration
          - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npm run type-check

      - name: Build Integration
        if: github.event.inputs.environment == 'integration'
        run: npm run build-integration

      - name: Build Production
        if: github.event.inputs.environment == 'production'
        run: npm run build